#!/bin/bash

set -e

. test/test_helper.sh

echo -n "Sort by sequence length... "
r1=$(bin/merge_sort \
  test/data/test.fasta /dev/stdout \
  --buffer 1 \
  --tempdir . \
  --key "lambda k: len(k.seq)" | md5 -q)

should $r1 'dd6bc352792d3342fa6543303f10dbe4'

echo -n "Sort by description (alphanumeric)... "
r2=$(bin/merge_sort \
  test/data/test.fasta /dev/stdout \
  --buffer 1 \
  --tempdir . \
  --key "lambda k: k.description" | md5 -q)

should $r2 'dd6bc352792d3342fa6543303f10dbe4'
